### PR TITLE
Check connection with Ceph

### PR DESCRIPTION
**Pull request by fridex**
Fixes: #17

### CODE REVIEW

**Comment by fridex** [comment]
Marking as WIP as this needs https://github.com/thoth-station/storages/pull/23 and a new thoth-storages release.

**Comment by goern** [comment]
/lgtm
what about the wip label?

**Comment by fridex** [comment]
> what about the wip label?

I need to release new storages that have the check method. Do we want to have it released with tests introduced in https://github.com/thoth-station/storages/pull/21?

**Pull request merged**
